# Generated by Django 3.2 on 2022-10-05 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothe',
            name='closet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='clothes', to='closet.closet'),
            preserve_default=False,
        ),
    ]
