# Generated by Django 3.2 on 2022-10-05 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0002_clothe_closet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='static/images/icon-svg/anonymous.png', upload_to='images/profile_pictures'),
        ),
    ]
