# Generated by Django 3.2 on 2022-10-05 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0003_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='/images/profile_pictures/anonymous.png', upload_to='images/profile_pictures'),
        ),
    ]
