# Generated by Django 3.2 on 2022-10-05 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0004_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closets', to=settings.AUTH_USER_MODEL),
        ),
    ]
