# Generated by Django 3.2 on 2022-10-06 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0005_alter_closet_user'),
        ('market', '0002_post_is_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_posts', to='closet.clothe'),
        ),
    ]
