# Generated by Django 3.2 on 2022-10-06 09:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('market', '0003_alter_post_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionlog',
            name='user',
        ),
        migrations.AddField(
            model_name='transactionlog',
            name='address',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactionlog',
            name='buyer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='bought_transaction', to='closet.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactionlog',
            name='done',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactionlog',
            name='payment',
            field=models.IntegerField(choices=[(1, '貨到付款'), (2, '錢包付款')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactionlog',
            name='seller',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='sold_transaction', to='closet.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactionlog',
            name='wallet',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='market.wallet'),
            preserve_default=False,
        ),
    ]
