# Generated by Django 3.2 on 2022-10-06 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0005_alter_closet_user'),
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='clothes',
            field=models.ManyToManyField(blank=True, null=True, to='closet.Clothe'),
        ),
    ]
