# Generated by Django 3.2 on 2022-11-13 13:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0002_post_clothes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='follower',
            field=models.ManyToManyField(related_name='followedPosts', to=settings.AUTH_USER_MODEL),
        ),
    ]
